# Generated by Django 4.1.1 on 2022-09-13 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Instructors', '0007_rename_twitter_instructor_facebook'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.TextField(max_length=150)),
                ('course_price', models.IntegerField(default=0)),
                ('course_houre', models.IntegerField(default=0)),
                ('course_Student', models.IntegerField(default=0)),
                ('course_image', models.ImageField(default='image.png', upload_to='course_image')),
                ('course_rate', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('instructor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Course_instructor', to='Instructors.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(max_length=1500)),
                ('comment_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_owner', to=settings.AUTH_USER_MODEL)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_course', to='course.courses')),
            ],
        ),
    ]
