# Generated by Django 4.1.1 on 2022-09-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('job', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to='Instructor_image')),
                ('slug', models.SlugField(max_length=255)),
            ],
        ),
    ]
