# Generated by Django 4.1.1 on 2022-09-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categeory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
