# Generated by Django 4.1.1 on 2022-09-07 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0002_categeory'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='categeory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Instructors.categeory'),
            preserve_default=False,
        ),
    ]
