# Generated by Django 4.1.1 on 2022-09-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0003_instructor_categeory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
