# Generated by Django 4.1.1 on 2022-09-07 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0004_alter_instructor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='categeory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Instructors.categeory'),
        ),
    ]
