# Generated by Django 4.1.1 on 2022-09-11 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instructors', '0006_instructor_github_instructor_linkdin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='twitter',
            new_name='facebook',
        ),
    ]
